api_platform:
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  patch_formats:
    mime_types: ["multipart/form-data"]
  defaults:
    pagination_partial: true
