gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 86400
  # single_use: true

  # Use cookies for the refresh token
  cookie:
    enabled: true
    remove_token_from_body: true
    # Cookie parameters
    http_only: true
    same_site: strict
    secure: true
    path: /api/token
    domain: null
